---
- name: install php and modules
  apt: >
    name={{ item }}
  with_items:
    - php5
    - php5-cli
    - php5-common
    - php5-mysql
    - php5-curl
    - php5-dev
    - php5-fpm
    - php5-gd
    - php-pear
  notify: enable php5-fpm

- name: copy php5-fpm ini
  template: src=php.ini.j2 dest=/etc/php5/fpm/php.ini backup=yes
  notify: restart php5-fpm
