---
- name: install mysql
  apt: >
    name={{ item }}
  with_items:
    - mysql-server
    - python-mysqldb

- name: start mysql
  service: name=mysql state=started enabled=yes

- name: set the root password
  mysql_user: >
    name=root
    password="{{ mysql_root_password }}"
    check_implicit_admin=yes
    login_user=root
    login_password="{{ mysql_root_password }}"
    host={{ item }}
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: delete anonymous mysql server
  mysql_user: >
    name=""
    state=absent
    login_user=root
    login_password="{{ mysql_root_password }}"
    host={{ item }}
  with_items:
    - "{{ ansible_hostname }}"
    - localhost

- name: remove the test database
  mysql_db: >
    db=test
    state=absent
    login_user=root
    login_password="{{ mysql_root_password }}"
